### PR TITLE
Fixed : "Add the descrive about the control event that is target of the "P" layer event processing function." #15

### LINKED ISSUE #15: Add the descrive about the control event that is target of the "P" layer event processing function.
# Requirement
Append explanation to "user guides" depending on the following changes.

### user guides
- /documents/1_User_Guide/en/1_User_Guide(Common)_EN.doc
- /documents/1_User_Guide/en/2_User_Guide(Leaders)_EN.doc
- /documents/1_User_Guide/ja-JP/1_User_Guide(Common).doc
- /documents/1_User_Guide/ja-JP/2_User_Guide(Leaders).doc

### changes
- [Support of event handling of the TextBox Class (System.Web.UI.WebControls) #80](https://github.com/OpenTouryoProject/OpenTouryo/issues/80)

### PR DESCRIPTION
**Pull request by daisukenishino**
Fixed #15

# Correspondence of #15 and, other updates.

### Correspondence of #15
Add the descrive about the control event that is target of the "P" layer event processing function.

### Other updates
- Updated, such as date.
- Updated the information that is related current supported products and the product version.
- Fixes of existing problem
  - Trimmed the document style for the English version document.
  - Edited the problems of English version document.
    - Toryo ---> Touryo ---> Open Touryo.
    - Change to single-byte characters from double-byte characters.
    - Unify of the description.
    - Changed the font.
  - , etc.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

It is written on a cover of [1_User_Guide(Common)_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/NewCntrlEvent/documents/1_User_Guide/en/1_User_Guide(Common)_EN.doc) as follows:
```txt
"Open Touryo".NET application framework user guide (index edition)
```

I think that this document is *common* edition.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please revise as follows:
- 内容物一覧.xlsx -> *Content_list.xlsx*
- 機能一覧.xls -> *Functional_list.xlsx*
- ユーザ利用API一覧.xls -> ???  
(Corresponding document is missing)
- APIリファレンス マニュアル.zip -> *1a_API_Reference_Manual.zip*

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please revise the character '～' in English document as follows:
- When using this character in the sense of *range*, please use 'to'.
    - ex: *100 ～ 200* -> *100 to 200*.
- When using this character in the sense of *omission*, please use '...'.
    - ex: *～ \root folder* -> *...\root folder*.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please merge because these were fixed.
see: https://github.com/OpenTouryoProject/OpenTouryoDocuments/pull/18/commits

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> Please revise as follows:
> - 内容物一覧.xlsx -> *Content_list.xlsx*
> - 機能一覧.xls -> *Functional_list.xlsx*
> - ユーザ利用API一覧.xls -> ???  
> (Corresponding document is missing)
> - APIリファレンス マニュアル.zip -> *1a_API_Reference_Manual.zip*

Please revise one more thing.
- configParameterlist.xls, configパラメタ一覧.xls -> *1b_config_parameter_list.xls*

I will merge this pull request when the above is revised.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>Please revise one more thing.
- configParameterlist.xls, configパラメタ一覧.xls -> *1b_config_parameter_list.xls*
>
I will merge this pull request when the above is revised.

I see. I will fix this in today's last time.

If you find other modifications,
please add it to Github-comment in today.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please merge after confirming [the additional commit](https://github.com/OpenTouryoProject/OpenTouryoDocuments/pull/18/commits/22f4b3fdbfdda2b61d61b1f9b8980f6290736c1b).

And, there are the additional fixes.
 I've add the following modifications to the index edited.
- Updated, such as date.
- Toryo ---> Touryo ---> Open Touryo.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

- Please revise the cover of *ja-JP\2_User_Guide(Leaders).doc* as follows:
    - 棟梁 -> Open 棟梁
- In English document, the date format in *document header* is different from the one in *main text*.  
Please use American style.
    - document header: 2016/10/3 (yyyy/mm/dd, Japanese style)
    - main text: 10/3/2016 (mm/dd/yyyy, American style)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please merge after confirming [the additional commit](https://github.com/OpenTouryoProject/OpenTouryoDocuments/pull/18/commits/b2dfc94d0fb4740e9f96e6ab30c454312b9cc140).

And, there are the additional fixes.
I've add the following modifications to the all editions.
- Updated, such as date.
- Toryo ---> Touryo ---> Open Touryo.
- Set the style of the header-footer to the same style.
- Just in case, Updated the table of contents at the end.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please revise the cover of *3_User_Guide(Developers)_EN.doc* as follows:
- 10/3/2014 -> 10/3/2016

**Pull request merged**
